### PR TITLE
UX: Styling adjustments

### PR DESCRIPTION
**Pull request by pmusaraj**
The styling changes affect both desktop and mobile, but most visible differences are on mobile. 

Before: 

image

After: 

image

### CODE REVIEW

**Comment by CvX** [comment]
I don't know if it's caused by the changes in this PR but frontend tests are failing. (also saw a backend flake on the first CI run)

**Comment by pmusaraj** [comment]
Test failures look legit, will take a look shortly.

**Comment by tgxworld** [comment]
Screenshot from 2022-03-18 10-05-52

On mobile I spotted a small overlap but I guess we need to figure out a way to hide the expand post replies button anyway.

**Review by tgxworld — APPROVED** [review]

**Comment by pmusaraj** [comment]
> Screenshot from 2022-03-18 10-05-52
> 
> On mobile I spotted a small overlap but I guess we need to figure out a way to hide the expand post replies button anyway.

Right. I don't see the "Reply" button next to each answer, so I think this is a non-issue. You probably had a reply to a post in your stream before the plugin disabled those buttons.

**Comment by tgxworld** [comment]
O right that is also not allowed any more because I have a validation that prevents rely to any post which is not the first.

**Pull request merged**
